<?xml version="1.0"?>
<robot name="camera" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <link name="camera_link">
    <visual>
      <geometry>
        <box size="${camera_width} ${camera_length} ${camera_height}"/>
      </geometry>

      <origin xyz="0 0 0" rpy="0 0 ${pi/2}"/>
      <material name="black"/>
    </visual>

    <collision>
      <geometry>
        <box size="${camera_width} ${camera_length} ${camera_height}"/>
      </geometry>

      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>

    <xacro:box_inertia m="0.5" l="${camera_length}"
                               w="${camera_width}"
                               h="${camera_height}"
                               xyz="0 0 0" rpy="0 0 0"/>
  </link>

  <joint name="base_camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="0.3 0 ${(base_height / 2) - 0.1}" rpy="0 0 0"/>
  </joint>


  <gazebo reference="camera_link">

    <material>Gazebo/Black</material>

    <sensor name="camera_sansor" type="camera">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>10.0</update_rate>

      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <frame_name>camera_link</frame_name>
      </plugin>
    </sensor>

  </gazebo>

</robot>