<?xml version="1.0"?>
<robot name="lidar" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
      </geometry>

      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="black"/>
    </visual>

    <collision>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
      </geometry>

      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>

    <xacro:cylinder_inertia m="0.2" r="${lidar_radius * 2}"
                                 l="${lidar_length * 2}"
                                 xyz="0 0 0" rpy="0 0 0"/>
  </link>

  <joint name="base_lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 ${(base_height) + (lidar_length / 2) + 0.04}" rpy="0 0 0"/>
  </joint>

  <gazebo reference="lidar_link">
    <material>Gazebo/Black</material>

    <sensor name="lidar_sensor" type="ray">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>10.0</update_rate>
      
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
          </horizontal>
        </scan>

        <range>
          <min>0.1</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
      </ray>

      <plugin name="lidar" filename="libgazebo_ros_ray_sensor.so">
        <output_type>sensor_msgs/LaserScan</output_type>
      </plugin>  
    </sensor>
  </gazebo>

</robot>